import assert from 'node:assert/strict'; import test from 'node:test';
import { analyzeDeckStructure, importCommanderDeck, LocalCatalogCardReferenceProvider } from '../../../src/index.js'; import { loadCatalog } from '../../../src/adapters/card-reference/local-catalog-loader.js'; import { card, provenance } from '../../fixtures/structural-card-catalog.js';
import type { ImportResult } from '../../../src/domain/deck-import/import-result.js';
const provider = new LocalCatalogCardReferenceProvider(loadCatalog({ cards: [card('Commander', { canonicalManaValue: 4, normalTopLevelTypes: ['Creature'], colorIdentity: ['W', 'U'] }), card('Artifact Creature', { canonicalManaValue: 3, normalTopLevelTypes: ['Artifact', 'Creature'] }), card('Forest', { canonicalManaValue: 0, normalTopLevelTypes: ['Land'] }), card('Spell // Land', { canonicalManaValue: 3, normalTopLevelTypes: ['Sorcery'], colorIdentity: ['G'], hasAlternativeLandFace: true })], provenance }));
test('reports exact deterministic structural facts for a complete deck', async () => { const analysis = analyzeDeckStructure(await importCommanderDeck('Commander\n1 Commander\nDeck\n2 Artifact Creature\n1 Forest\n1 Spell // Land', provider)); assert.deepEqual(analysis.coverage, { resolvedCardQuantity: 5, unresolvedCardQuantity: 0, importedCardQuantity: 5, hasUnresolvedCommander: false, status: 'complete' }); assert.equal(analysis.declaredDeckCardQuantity, 5); assert.equal(analysis.resolvedCommanderQuantity, 1); assert.equal(analysis.resolvedLibraryQuantity, 4); assert.equal(analysis.resolvedLandQuantity, 1); assert.equal(analysis.resolvedNonlandQuantity, 4); assert.deepEqual(analysis.typeComposition, [{ topLevelType: 'Artifact', quantity: 2 }, { topLevelType: 'Creature', quantity: 3 }, { topLevelType: 'Land', quantity: 1 }, { topLevelType: 'Sorcery', quantity: 1 }]); assert.deepEqual(analysis.alternativeLandFaceCards.map(c => c.identity.canonicalName), ['Spell // Land']); assert.deepEqual(analysis.manaValue, { totalManaValue: 13, averageManaValue: { status: 'available', value: 3.25 }, distribution: [{ manaValue: 3, quantity: 3 }, { manaValue: 4, quantity: 1 }] }); assert.deepEqual(analysis.commanderColorIdentity, { status: 'complete', colors: ['W', 'U'] }); assert.deepEqual(analysis.cardDataVersionsUsed, ['v1:2026-01-01T00:00:00Z']); });
test('keeps resolved structural facts separate for a partial import', async () => { const partial = analyzeDeckStructure(await importCommanderDeck('Commander\n1 Missing\nDeck\n1 Forest', provider)); assert.deepEqual(partial.coverage, { resolvedCardQuantity: 1, unresolvedCardQuantity: 1, importedCardQuantity: 2, hasUnresolvedCommander: true, status: 'partial' }); assert.equal(partial.declaredDeckCardQuantity, 2); assert.equal(partial.resolvedCommanderQuantity, 0); assert.equal(partial.resolvedLibraryQuantity, 1); assert.equal(partial.resolvedLandQuantity, 1); assert.equal(partial.resolvedNonlandQuantity, 0); assert.deepEqual(partial.typeComposition, [{ topLevelType: 'Land', quantity: 1 }]); assert.deepEqual(partial.commanderColorIdentity, { status: 'incomplete', colors: [] }); assert.deepEqual(partial.cardDataVersionsUsed, ['v1:2026-01-01T00:00:00Z']); assert.deepEqual(partial.manaValue, { totalManaValue: 0, averageManaValue: { status: 'unavailable' }, distribution: [] }); });
test('exports a provider-free structural analyzer for normalized import results', () => { const normalized: ImportResult = { resolvedContent: [
  { identity: { canonicalKey: 'card:second', canonicalName: 'Second' }, characteristics: { canonicalManaValue: 2, normalTopLevelTypes: ['Artifact'], colorIdentity: [], hasAlternativeLandFace: false }, quantity: 1, commanderDesignated: false, sourceEntries: [], resolutionEvidence: { resolutionKind: 'exact-match', normalizedLookupName: 'second', cardDataVersion: 'catalog-v2' } },
  { identity: { canonicalKey: 'card:first', canonicalName: 'First' }, characteristics: { canonicalManaValue: 1, normalTopLevelTypes: ['Creature'], colorIdentity: ['W'], hasAlternativeLandFace: false }, quantity: 1, commanderDesignated: true, sourceEntries: [], resolutionEvidence: { resolutionKind: 'exact-match', normalizedLookupName: 'first', cardDataVersion: 'catalog-v1' } },
  { identity: { canonicalKey: 'card:duplicate-version', canonicalName: 'Duplicate Version' }, characteristics: { canonicalManaValue: 3, normalTopLevelTypes: ['Instant'], colorIdentity: [], hasAlternativeLandFace: false }, quantity: 1, commanderDesignated: false, sourceEntries: [], resolutionEvidence: { resolutionKind: 'exact-match', normalizedLookupName: 'duplicate version', cardDataVersion: 'catalog-v2' } },
], problems: [], sourceEntries: [], inputOutcome: 'deck-entries-supplied', commanderOutcome: 'designated-and-resolved' };
  const analysis = analyzeDeckStructure(normalized);
  assert.equal(analysis.declaredDeckCardQuantity, 3);
  assert.deepEqual(analysis.cardDataVersionsUsed, ['catalog-v1', 'catalog-v2']);
});
