import assert from 'node:assert/strict'; import { createHash } from 'node:crypto'; import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'; import test from 'node:test'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { LocalCatalogCardReferenceProvider } from '../../../src/adapters/card-reference/local-catalog-card-reference-provider.js';
import { loadCatalog } from '../../../src/adapters/card-reference/local-catalog-loader.js';
import { LocalCatalogStore, type StoredCatalog } from '../../../src/adapters/card-reference/local-catalog-store.js';
test('resolves exact normalized names from loaded catalog', async () => { const provider = new LocalCatalogCardReferenceProvider(loadCatalog({ cards: [{ name: 'Sol Ring' }], provenance: { provider: 'fixture', datasetKind: 'oracle_cards', providerDatasetId: 'v1', providerUpdatedAt: 'now', sourceDownloadUri: 'fixture', declaredSize: 1, acquiredAt: 'now' } })); const result = (await provider.resolveExactNames(['sol ring'])).get('sol ring')!; assert.equal(result.kind, 'exact-match'); if (result.kind === 'exact-match') assert.equal(result.identity.canonicalName, 'Sol Ring'); });
async function activeGeneration(dir: string): Promise<string> { return (JSON.parse(await readFile(join(dir, 'active.json'), 'utf8')) as { generation: string }).generation; }
const provenance = { provider: 'fixture', datasetKind: 'oracle_cards', providerDatasetId: 'v1', providerUpdatedAt: 'now', sourceDownloadUri: 'fixture', declaredSize: 1, acquiredAt: 'now' };
test('rejects catalog records with an invalid card shape', async () => { const dir = await mkdtemp(join(tmpdir(), 'manalab-')); try { const store = new LocalCatalogStore(dir); await store.replace([{ name: 'Sol Ring' }], provenance); const root = join(dir, 'generations', await activeGeneration(dir)); const payload = '{"name":42}\n'; await writeFile(join(root, 'catalog.jsonl'), payload); const metaPath = join(root, 'catalog.meta.json'); const meta = JSON.parse(await readFile(metaPath, 'utf8')) as Record<string, unknown>; meta.localContentDigest = createHash('sha256').update(payload).digest('hex'); await writeFile(metaPath, JSON.stringify(meta)); assert.equal(await store.load(), undefined); } finally { await rm(dir, { recursive: true, force: true }); } });
test('rejects a catalog with missing required provenance', async () => { const dir = await mkdtemp(join(tmpdir(), 'manalab-')); try { const store = new LocalCatalogStore(dir); await store.replace([{ name: 'Sol Ring' }], provenance); const root = join(dir, 'generations', await activeGeneration(dir)); await writeFile(join(root, 'catalog.meta.json'), JSON.stringify({})); assert.equal(await store.load(), undefined); } finally { await rm(dir, { recursive: true, force: true }); } });
test('rejects a catalog whose recorded content digest does not match', async () => { const dir = await mkdtemp(join(tmpdir(), 'manalab-')); try { const store = new LocalCatalogStore(dir); await store.replace([{ name: 'Sol Ring' }], provenance); const root = join(dir, 'generations', await activeGeneration(dir)); await writeFile(join(root, 'catalog.jsonl'), '{"name":"Arcane Signet"}\n'); assert.equal(await store.load(), undefined); } finally { await rm(dir, { recursive: true, force: true }); } });
test('does not activate an invalid replacement candidate', async () => { const dir = await mkdtemp(join(tmpdir(), 'manalab-')); try { const store = new LocalCatalogStore(dir); await store.replace([{ name: 'Sol Ring' }], provenance); await assert.rejects(store.replace([{ name: '' }], provenance)); assert.deepEqual((await store.load())?.cards, [{ name: 'Sol Ring' }]); } finally { await rm(dir, { recursive: true, force: true }); } });
test('rejects invalid records and provenance at the direct loader boundary', () => { assert.throws(() => loadCatalog({ cards: [{ name: '' }], provenance } as unknown as StoredCatalog)); assert.throws(() => loadCatalog({ cards: [{ name: 'Sol Ring' }], provenance: {} } as unknown as StoredCatalog)); });
test('rejects duplicate normalized names rather than selecting one arbitrarily', () => { assert.throws(() => loadCatalog({ cards: [{ name: 'Sol Ring' }, { name: 'SOL  RING' }], provenance })); });
