import { createHash } from 'node:crypto'; import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises'; import { join } from 'node:path'; import { normalizeName } from '../../domain/deck-import/normalize-entry.js';
export interface CatalogProvenance { provider: string; datasetKind: string; providerDatasetId: string; providerUpdatedAt: string; sourceDownloadUri: string; declaredSize: number; acquiredAt: string; localContentDigest?: string }
export interface StoredCatalog { cards: { name: string }[]; provenance: CatalogProvenance }
function isCatalogProvenance(value: unknown): value is CatalogProvenance {
  if (!value || typeof value !== 'object') return false;
  const provenance = value as Record<string, unknown>;
  return ['provider', 'datasetKind', 'providerDatasetId', 'providerUpdatedAt', 'sourceDownloadUri', 'acquiredAt'].every(field => typeof provenance[field] === 'string' && provenance[field].length > 0)
    && typeof provenance.declaredSize === 'number' && Number.isFinite(provenance.declaredSize) && provenance.declaredSize >= 0
    && (provenance.localContentDigest === undefined || typeof provenance.localContentDigest === 'string');
}
function isCardRecord(value: unknown): value is { name: string } { return !!value && typeof value === 'object' && typeof (value as { name?: unknown }).name === 'string' && (value as { name: string }).name.trim().length > 0; }
function hasUniqueNormalizedNames(cards: readonly { name: string }[]): boolean { return new Set(cards.map(card => normalizeName(card.name))).size === cards.length; }
export function isValidStoredCatalog(value: unknown): value is StoredCatalog { if (!value || typeof value !== 'object' || !Array.isArray((value as { cards?: unknown }).cards)) return false; const cards = (value as { cards: unknown[] }).cards; return cards.length > 0 && cards.every(isCardRecord) && hasUniqueNormalizedNames(cards) && isCatalogProvenance((value as { provenance?: unknown }).provenance); }
export class LocalCatalogStore {
  constructor(private readonly directory: string) {}
  private get activePath() { return join(this.directory, 'active.json'); } private generationPath(id: string) { return join(this.directory, 'generations', id); }
  async load(): Promise<StoredCatalog | undefined> { try { const { generation } = JSON.parse(await readFile(this.activePath, 'utf8')) as { generation?: unknown }; if (typeof generation !== 'string' || !generation) return undefined; const root = this.generationPath(generation); const [data, meta] = await Promise.all([readFile(join(root, 'catalog.jsonl'), 'utf8'), readFile(join(root, 'catalog.meta.json'), 'utf8')]); const stored: unknown = { cards: data.trim().split('\n').filter(Boolean).map(line => JSON.parse(line)), provenance: JSON.parse(meta) }; if (!isValidStoredCatalog(stored)) return undefined; if (stored.provenance.localContentDigest && createHash('sha256').update(data).digest('hex') !== stored.provenance.localContentDigest) return undefined; return stored; } catch { return undefined; } }
  async replace(cards: { name: string }[], provenance: CatalogProvenance): Promise<void> { if (!isValidStoredCatalog({ cards, provenance })) throw new Error('Invalid catalog replacement candidate.'); await mkdir(join(this.directory, 'generations'), { recursive: true }); const generation = `${Date.now()}-${Math.random().toString(36).slice(2)}`, root = this.generationPath(generation), payload = cards.map(card => JSON.stringify(card)).join('\n') + '\n', meta = { ...provenance, localContentDigest: createHash('sha256').update(payload).digest('hex') }; await mkdir(root); await Promise.all([writeFile(join(root, 'catalog.jsonl'), payload), writeFile(join(root, 'catalog.meta.json'), JSON.stringify(meta))]); const pointer = `${this.activePath}.${generation}.tmp`; try { await writeFile(pointer, JSON.stringify({ generation })); await rename(pointer, this.activePath); } finally { await rm(pointer, { force: true }); } }
}
